# Generated by Django 5.0.4 on 2024-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='blog/'),
        ),
    ]
